### ISSUE TITLE
"View User's Score" CSS Styling Issues

### ISSUE THREAD

**Issue by mtthwbckmn** [QuizandSurveyMaster/qsm-gradebook#3]
## General description

In the backend of WordPress, when viewing the list of user's, the hover state of the "View User's Score" link has a black background with the default blue WordPress text. The text is also 14 pixels instead of the default 13 pixels, and uses the **!important** tag to define the font size.
## Expected behavior

Default WordPress styling.
## Actual behavior

Black background on hover, along with slightly larger text.
## Steps to reproduce the behavior

Default behavior for the plugin.

**Comment by fpcorso** [comment]
Merged in #4
